-- Add Polish translations for all remaining scenario options

UPDATE scenario_options SET option_text_pl = 'Odłóż na później' WHERE id = 11;
UPDATE scenario_options SET option_text_pl = 'Lokata (bezpieczne)' WHERE id = 12;
UPDATE scenario_options SET option_text_pl = 'Fundusz (ryzykowne)' WHERE id = 13;
UPDATE scenario_options SET option_text_pl = 'Masz ubezpieczenie' WHERE id = 14;
UPDATE scenario_options SET option_text_pl = 'Bez ubezpieczenia' WHERE id = 15;
UPDATE scenario_options SET option_text_pl = 'Zmień pracę' WHERE id = 16;
UPDATE scenario_options SET option_text_pl = 'Zostań' WHERE id = 17;
UPDATE scenario_options SET option_text_pl = 'Przyjmij to' WHERE id = 18;
UPDATE scenario_options SET option_text_pl = 'Odmów' WHERE id = 19;
UPDATE scenario_options SET option_text_pl = 'Negocjuj' WHERE id = 20;
UPDATE scenario_options SET option_text_pl = 'Unikaj' WHERE id = 21;
UPDATE scenario_options SET option_text_pl = 'Fast food' WHERE id = 22;
UPDATE scenario_options SET option_text_pl = 'Gotuj w domu' WHERE id = 23;
UPDATE scenario_options SET option_text_pl = 'Zrób to' WHERE id = 24;
UPDATE scenario_options SET option_text_pl = 'Pomiń' WHERE id = 25;
UPDATE scenario_options SET option_text_pl = 'Sesje fizjoterapii' WHERE id = 26;
UPDATE scenario_options SET option_text_pl = 'Ignoruj' WHERE id = 27;
UPDATE scenario_options SET option_text_pl = 'Bootcamp' WHERE id = 28;
UPDATE scenario_options SET option_text_pl = 'Samodzielna nauka' WHERE id = 29;
UPDATE scenario_options SET option_text_pl = 'Zapisz się' WHERE id = 30;
UPDATE scenario_options SET option_text_pl = 'Pomiń' WHERE id = 31;
UPDATE scenario_options SET option_text_pl = 'Zapłać i podejdź do egzaminu' WHERE id = 32;
UPDATE scenario_options SET option_text_pl = 'Poczekaj' WHERE id = 33;
UPDATE scenario_options SET option_text_pl = 'Wprowadź się' WHERE id = 34;
UPDATE scenario_options SET option_text_pl = 'Zostań osobno' WHERE id = 35;
UPDATE scenario_options SET option_text_pl = 'Zapewnij wsparcie' WHERE id = 36;
UPDATE scenario_options SET option_text_pl = 'Ograniczona pomoc' WHERE id = 37;
UPDATE scenario_options SET option_text_pl = 'Adoptuj' WHERE id = 38;
UPDATE scenario_options SET option_text_pl = 'Nie teraz' WHERE id = 39;
UPDATE scenario_options SET option_text_pl = 'Oszczędzaj miesięcznie' WHERE id = 40;
UPDATE scenario_options SET option_text_pl = 'Pomiń na razie' WHERE id = 41;
UPDATE scenario_options SET option_text_pl = 'Spłacaj agresywnie' WHERE id = 42;
UPDATE scenario_options SET option_text_pl = 'Tylko minimum' WHERE id = 43;
UPDATE scenario_options SET option_text_pl = 'Oszczędzaj na wkład własny' WHERE id = 44;
UPDATE scenario_options SET option_text_pl = 'Wynajmuj dłużej' WHERE id = 45;
UPDATE scenario_options SET option_text_pl = 'Trzymaj' WHERE id = 46;
UPDATE scenario_options SET option_text_pl = 'Sprzedaj w panice' WHERE id = 47;
UPDATE scenario_options SET option_text_pl = 'Zbuduj poduszkę finansową' WHERE id = 48;
UPDATE scenario_options SET option_text_pl = 'Ignoruj' WHERE id = 49;
UPDATE scenario_options SET option_text_pl = 'Użyj funduszu awaryjnego' WHERE id = 50;
UPDATE scenario_options SET option_text_pl = 'Pożycz' WHERE id = 51;