// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwnwrhopvjysluqtvdgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3bndyaG9wdmp5c2x1cXR2ZGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NTY3MTksImV4cCI6MjA3NTEzMjcxOX0.NCzNv6lFVIFS8snsz2SgoHiBWy6Z2zNpYqf0f8vIkS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});